### DISCUSSION TITLE
Results Verification

### DISCUSSION THREAD

**Discussion by AidanMcDonald** [terrapower/armicontrib-openmc#7] [Q&A]
How should I be verifying that the results generated by this plugin are correct? I assume there's an established way.

**Comment by jakehader** [comment]
Hey @AidanMcDonald - I wonder if we could build GitHub CI that would build OpenMC and run the `C5G7` problem as an integration test. @john-science do you think this would be difficult to support on this repository? Maybe using the docker container - https://docs.openmc.org/en/stable/usersguide/install.html#installing-on-linux-mac-windows-with-docker

**Reply by john-science** [reply]
Using GitHub CI would be the best, for sure.

ARMI already uses lots of linux-based GitHub Actions, so that's really easy to do: https://github.com/terrapower/armi/blob/main/.github/workflows/linting.yaml#L8

Do you need to download things from online to install OpenMC, or get data? That could be a little tricky. But you would basically just copy/paste your linux commands into the CI script, and they should work.

**Reply by john-science** [reply]
Do you need some help with that, Aidan?

**Reply by AidanMcDonald** [reply]
This is a great idea and hopefully doable, but I will likely need some help getting started with it.

Beyond retrieving OpenMC itself, we have to download a cross section library (OpenMC provides precompiled ones [here](https://openmc.org/official-data-libraries/)) and set the `OPENMC_CROSS_SECTIONS` environment variable to point to it.

Ideally I would like tests using both multigroup and continuous energy cross sections, and it's possible the multigroup test could bypass the need to download a cross section library if the download is a problem. In my first couple attempts, OpenMC crashed complaining about not having a continuous energy cross section library despite not needing one for a multigroup run, but it seems like there should be a way to make that work.

I personally haven't ever installed OpenMC with Docker (I always compile from source), but I assume that will be the way to go and will work fine.

**Reply by john-science** [reply]
You can execute BASH commands in a GitHub Action. So, I imagine something like this (at something like `.github/workflows/testing.yaml` in your repo):

```yaml
name: Results Verificaiton

permissions:
  contents: read

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Run Results
        shell: bash
        env:
          OPENMC_CROSS_SECTIONS: SOMETHING_OR_WHATEVER
        run: |
          pip install -U pip
          pip install -e .
          wget https://anl.box.com/shared/static/9igk353zpy8fn9ttvtrqgzvw1vtejoz6.xz  # this is a guess
          wget openMC # TODO? How?
          # somehow build openmc?  Maybe "cd openmc;make" ?
          python run/my/fancy/test.py
```

Okay, I'm real light on examples, but maybe we can work on it together?  And if you open a PR, you can test it out yourself. Live.
